### ISSUE TITLE
Side bar labels on homepage incorrect

### ISSUE THREAD

**Issue by sroosa** [WGBH/bostonlocaltv#215]
In the sidebar on the homepage there is a resources section. The labels under that are currently:
Archivists (linking to http://bostonlocaltv.wgbh-mla.org/blog/resources-archivist/)
Teachers (linking to http://bostonlocaltv.wgbh-mla.org/blog/resources-for-scholars/)
Students (linking to http://bostonlocaltv.wgbh-mla.org/blog/resources-for-teachers/)

These should be changed to 
Archivists (linking to http://bostonlocaltv.wgbh-mla.org/blog/resources-archivist/)
Scholars (linking to http://bostonlocaltv.wgbh-mla.org/blog/resources-for-scholars/)
Teachers (linking to http://bostonlocaltv.wgbh-mla.org/blog/resources-for-teachers/)

**Comment by mccalluc** [comment]
@sroosa : If you look at the source, you'll see that these are expressed as "/blog/resources-archivist" etc.: The hostname is implicit. This is a good practice because it means when you're looking at a demo site and trying to find bugs, you won't get shifted over to the live site without realizing it. Ok?

**Comment by sroosa** [comment]
@mccalluc : Okay.
