### ISSUE TITLE
request digitization button

### ISSUE THREAD

**Issue by mccalluc** [WGBH/bostonlocaltv#231]
@sroosa : So I'll add a button above the empty player (I may get rid of the empty player, since it just looks broken...), and that will bring up a modal? What text do you want in the modal? Is the messaging different for different collections?

**Comment by sroosa** [comment]
@mccalluc : I'd actually like to keep the empty player. Our intension was to make it look like a player with nothing to play, which is why it has the text : This assets hasn't been digitized yet. We wanted to convey that it could be playable, if it is digitized. 
As for the modal:

You can contribute to the digitization of materials in the Boston TV News Digital Library. Costs and timelines vary between items, but explain your interests via [email] (loads form email), and we will work with you to make more local Boston news content available to the world.

The email that it makes can be very much like the one for Open Vault, and can be sent directly to me at sadie_roosa@wgbh.org.
