### ISSUE TITLE
Sort by year totally broken

### ISSUE THREAD

**Issue by mccalluc** [WGBH/bostonlocaltv#264]
On both the live site and the beta, sort by year is broken: It pops you to the homepage with an error message.

**Comment by jasoncorum** [comment]
Initial Notes: This one looks like it is caused by the fact that a date_s field is included in add_sort_field method in the CatalogController. The DynamicFields in the schema.xml define *_s fields as multiValued which is a no no for sorting. I think the date_s is there as a secondary sort after year_i - which would be a good idea since just year won't get you a good sort. But we need to specify that secondary sorting field and make sure that it isn't multiValued.

**Comment by jasoncorum** [comment]
Here's sorting by year not throwing an error and properly sorting secondarily on date created in my development environment.
![screen shot 2016-12-12 at 11 10 11 am](https://cloud.githubusercontent.com/assets/3814190/21242339/dc041db6-c2e1-11e6-837f-ecfc2426036f.png)
