### ISSUE TITLE
Re-establish BLTV OAI endpoint

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/bostonlocaltv#277]
However, it looks like the OAI endpoint information supplied in the application may no longer be valid? I'm not getting any records returned with any of the URL permutations below...

http://bostonlocaltv.org/catalog/oai?verb=ListRecords

http://bostonlocaltv.org/catalog/oai.xml?verb=ListRecords

This will be primarily for harvesting by Digital Commonwealth. Should probably be similar to the ones for AAPB.

**Comment by sroosa** [comment]
Turns out this was never an issue with the actual OAI endpoint, but rather a data problems. AT some point an ingest had a record missing a require field. The OAI code wasn't built to handle a missing field, so it errored. That data has been corrected, and it now works as an API endpoint, although doesn't give you results if you just hit in the browser.
